FROM node:20.12.0-alpine3.19

WORKDIR /user/src/app

COPY package.json package-lock.json turbo.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm install

# Generate prisma client
RUN npm run db:generate

# Build the app
RUN npm run build

CMD ["npm", "run", "start-user-app"]